### ISSUE TITLE
javascript source?

### ISSUE THREAD

**Issue by tablatronix** [JRodrigoTech/ESP32-Reflow-Toaster-Oven-Controller#1]
Do you have the js source raw?

```C++
// Live Canvas Graphing Scripts //
static const String mainscripts = 
```

**Comment by tablatronix** [comment]
oh nm, I decoded it and it is not minified! Nice

**Comment by JRodrigoTech** [comment]
Yes, is encoded in base64 to place it on code more easily, any online decoder can reverse it =)
